### ISSUE TITLE
Installation in Redmatic schägt fehl

### ISSUE THREAD

**Issue by ThomasLoeffel** [egs2003/node-red-contrib-doorbird#1]
Hallo Zusammen,

bei mir lässt sich diese node nicht installieren. Unter Iobroker geht es, aber unter Redmatic / Ausus/Tinkerboad nicht.

Gruß
Thomas

Angezeigter Fehler hängt ggf. mit:
Error: Can't find Python executable "python", you can set the PYTHON env variable.

zusammen......

**Comment by egs2003** [comment]
Dann bitte Python installieren
