### ISSUE TITLE
Plötzlich error in decryption

### ISSUE THREAD

**Issue by Tscherno** [egs2003/node-red-contrib-doorbird#2]
Hi,

ich habe die Node am Anfang erfolgreich verwendet. Jetzt scheint die Entschlüsselung gar nicht mehr zu funktionieren, ohne dass ich bewusst etwas geändert habe. Ich habe schon mehrere verschiedene User ausprobiert, aber das macht keinen Unterschied. Irgendwelche Ratschläge?

**Comment by egs2003** [comment]
Leider nein. Bei mir läuft bis heute alles zuverlässig. Gab es ein Update in letzter Zeit? Also von Doorbird?

**Comment by Prowling123** [comment]
![doorbirdnode](https://user-images.githubusercontent.com/75331898/100780942-a788a680-340a-11eb-8b4f-a6db13e1dc7d.jpg)
I'm sorry if this is a stupid question, but i started a flow like this and entered username and the udp inputs. I do not get any logs in the debug window. Is ther something else i would have to do?

**Comment by egs2003** [comment]
Nein, mehr gibt es nicht zu tun. Werden denn UDPs Pakete empfangen?

Am Di., 1. Dez. 2020 um 19:25 Uhr schrieb Prowling123 <
notifications@github.com>:

**Comment by egs2003** [comment]
Keine weiteren Anfragen
