### ISSUE TITLE
Cannot get this to work

### ISSUE THREAD

**Issue by Prowling123** [egs2003/node-red-contrib-doorbird#3]
![doorbirdnode](https://user-images.githubusercontent.com/75331898/100781344-309fdd80-340b-11eb-8e04-b5e3a75319e0.jpg)
I am sorry if this is a stupid questions, but i am not sure where else to turn. I made the flow like shown, put in the correct user and password, udp inputs, but i do not get any debug messages. Do you have some idea about where I made a mistake?

**Comment by Prowling123** [comment]
@egs2003 Ich glaube, ich habe das Problem gefunden. Wireshark hat mir die udp-Pakete gezeigt, aber nodered läuft in einem Docker-Container. UDP-Ports sind dort nicht verfügbar. (Google translate, mein Deutsch is nicht gut, entschuldigung!)

**Comment by egs2003** [comment]
Ich kann alles perfekt verstehen. Das klingt doch plausibel mit Docker und
UDP. Mit diesem Befehl könnte es aber klappen. -p 8080:80/udp

Am Di., 1. Dez. 2020 um 21:29 Uhr schrieb Prowling123 <
notifications@github.com>:

**Comment by Prowling123** [comment]
Ich habe eine services.yml gefunden, in der ich die udp-Ports hinzugefügt habe, die verfügbar gemacht werden sollen. Das nodeRed log sagt:

> 1 Dec 23:31:43 - [info] [udp in:bbe23a01.903518] udp listener at 0.0.0.0:6524
> 1 Dec 23:31:43 - [info] [udp in:ca427838.284998] udp listener at 0.0.0.0:35344


Es gibt immer noch keine Debug-Meldungen :(

**Comment by egs2003** [comment]
Dann kommen die Broadcast Pakete nicht bis in den Docker Container durch

Prowling123 <notifications@github.com> schrieb am Di., 1. Dez. 2020, 23:38:

**Comment by Prowling123** [comment]
ok I changed my docker-compose.yml and added 
    ports:
      - 1880:1880
      **- 6524:6524/udp
      - 35344:35344/udp**

The packets are now arriving. I made the following flow:
![doorb2](https://user-images.githubusercontent.com/75331898/100940155-c022ba80-34f7-11eb-8d6d-bea2fd672a3a.jpg)

Now however I am getting errors in decryption whenever i press the button. I think this is what the other topic is about

**Comment by Prowling123** [comment]
In the API Document from doorbird (which is from august 2019) it says they use Argon2i and ChaCha20. Is this what is being used by the code?

**Comment by egs2003** [comment]
Sind Benutzername und Kennwort richtig angegeben?

Prowling123 <notifications@github.com> schrieb am Mi., 2. Dez. 2020, 23:42:

**Comment by Prowling123** [comment]
Ja, diese sind korrekt eingegeben

**Comment by Prowling123** [comment]
Now it started working! There are still messages about encryption being wrong, but i changed the switch setting to " is true" and it started working anyway. Thanks for creating it!

**Comment by egs2003** [comment]
Woran lag es?

Prowling123 <notifications@github.com> schrieb am Do., 3. Dez. 2020, 22:46:
