### ISSUE TITLE
Wrong ELF Class

### ISSUE THREAD

**Issue by andispammonyer** [egs2003/node-red-contrib-doorbird#4]
Hi,

my Doorbird has Firmware 000128 and RedMatic is a Homematic Addon with Version 7.1.3.
I get the error from my doorbird redmatic module:
"Error: /usr/local/addons/redmatic/lib/node_modules/node-red-contrib-doorbird/node_modules/argon2/lib/binding/napi-v3/argon2.node: wrong ELF class: ELFCLASS64"

What is the issue?

**Comment by andispammonyer** [comment]
I installed the doorbird pakets via web interface
It was working well in the past with maybe RedMatic 6.x
![grafik](https://user-images.githubusercontent.com/68514976/102991591-d1b91a00-4519-11eb-9028-403dde72ac9d.png)

**Comment by PaHe77** [comment]
Hallo, 
ich habe das gleiche Problem. Gibt es schon ein Lösung ?
CCU3 - Redmatic 7.1.3 
Error: /usr/local/addons/redmatic/lib/node_modules/node-red-contrib-doorbird/node_modules/argon2/lib/binding/napi-v3/argon2.node: wrong ELF class: ELFCLASS64

**Comment by andispammonyer** [comment]
Ja und zwar downgrade zurück auf redmatic-6.0.4.tar.gz und alles ist wieder gut

**Comment by egs2003** [comment]
Mit redmatic nicht getestet. Offenbar läuft aber mit Downgrade alles
